name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
   sdk: ^3.0.0
  
dependencies:
  async_redux: ^20.0.2
  connectivity_plus: ^4.0.2
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  http_client:
    path: ../http_client
  logging: ^1.2.0
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  pro_lints: ^2.0.2
      
  
  