name: business
description: The business library.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  async_redux: ^15.0.0
  connectivity_plus: ^2.3.6
  fast_immutable_collections: ^7.4.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1 
  lint: 
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      href: '0e13a7c'
  
  