name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.4.1

dependencies:
  async_redux: ^23.0.2
  connectivity_plus: ^6.0.3
  fast_immutable_collections: ^10.2.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  http_client:
    path: ../http_client
  logging: ^1.2.0
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.4.10
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  pro_lints: ^2.0.4

dependency_overrides:
  meta: ^1.12.0

