name: business
description: The business library.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  async_redux: ^16.1.0
  connectivity_plus: ^2.3.7
  fast_immutable_collections: ^7.4.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.1
  dart_code_metrics: ^4.18.3
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.2
  lint: 
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      
  
  