name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  async_redux: ^19.0.2
  connectivity_plus: ^3.0.4
  fast_immutable_collections: ^9.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  http_client:
    path: ../http_client
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint: 
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      
  
  