name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  async_redux: ^24.0.2
  connectivity_plus: ^6.1.0
  fast_immutable_collections: ^11.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  http_client:
    path: ../http_client
  logging: ^1.3.0
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  pro_lints: ^2.0.4

dependency_overrides:
  meta: ^1.12.0

