name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.3.3

dependencies:
  async_redux: ^22.5.0
  connectivity_plus: ^6.0.1
  fast_immutable_collections: ^10.2.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.8
  http_client:
    path: ../http_client
  logging: ^1.2.0
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.8
  json_serializable: ^6.7.1
  pro_lints: ^2.0.2

dependency_overrides:
  connectivity_plus: ^6.0.1

