name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
   sdk: ^3.2.0

dependencies:
  async_redux: ^21.0.0
  connectivity_plus: ^5.0.1
  fast_immutable_collections: ^9.2.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  http_client:
    path: ../http_client
  logging: ^1.2.0
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  pro_lints: ^2.0.2


