name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
   sdk: ^3.0.0
  
dependencies:
  async_redux: ^20.0.2
  connectivity_plus: ^4.0.1
  fast_immutable_collections: ^9.1.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  http_client:
    path: ../http_client
  logging: ^1.2.0
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  pro_lints: ^2.0.1
      
  
  