name: business
description: The business library.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.3"

dependencies:
  async_redux: ^13.2.2
  chopper: ^4.0.5
  connectivity_plus: ^2.2.0
  fast_immutable_collections: ^7.2.0
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  json_annotation: ^4.4.0
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.5
  chopper_generator: ^4.0.5
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  
  