name: business
description: The business package.
publish_to: none
version: 1.0.0

environment:
   sdk: ^3.0.0
  
dependencies:
  async_redux: ^20.0.0
  connectivity_plus: ^4.0.1
  fast_immutable_collections: ^9.1.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  http_client:
    path: ../http_client
  models:
    path: ../models
  storage:
    path: ../storage

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  lint: 
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      
  
  