name: storybook
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization:
    path: ../../localization
  storybook_flutter: ^0.10.0
  ui:
    path: ../../ui


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  lint:
    path: ../../lint

flutter:
  uses-material-design: true