name: storybook
description: The Storybook project.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization:
    path: ../localization
  storybook_flutter: ^0.11.2+2
  ui:
    path: ../ui

dev_dependencies:
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'

flutter:
  uses-material-design: true