name: storybook
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization:
    path: ../localization
  storybook_flutter: ^0.11.1 
  ui:
    path: ../ui

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      href: '0e13a7c'

flutter:
  uses-material-design: true