name: utils
description: The utils library.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  chopper: ^5.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  logging: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.2
  chopper_generator: ^5.1.0+1
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      href: '41b64ec3bb748ec3b0fff7dba1ec31c5ee2db5fc'
  mockito: ^5.3.2
  test: ^1.22.0