name: utils
description: The utils library.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  chopper: ^4.0.5
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  logging: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.5
  chopper_generator: ^4.0.5
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      href: '41b64ec3bb748ec3b0fff7dba1ec31c5ee2db5fc'
  mockito: ^5.1.0
  test: ^1.16.4