name: http_client
description: The http_client package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  fast_immutable_collections: ^8.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  models:
    path: ../models
  retrofit: ^3.3.1

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"
  retrofit_generator: ^4.2.0