name: http_client
description: The http_client package.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^5.0.3
  fast_immutable_collections: ^9.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  logging: ^1.1.0
  models:
    path: ../models
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"
  retrofit_generator: ^6.0.0+1