name: http_client
description: The http_client package.
publish_to: none
version: 1.0.0

environment:
   sdk: ^3.3.3

dependencies:
  dio: ^5.4.2+1
  fast_immutable_collections: ^10.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  models:
    path: ../models
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.4.8
  json_serializable: ^6.7.1
  pro_lints: ^2.0.2
  retrofit_generator: ^8.1.0
