name: http_client
description: The http_client package.
publish_to: none
version: 1.0.0

environment:
   sdk: ^3.5.4

dependencies:
  dio: ^5.7.0
  fast_immutable_collections: ^11.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logging: ^1.3.0
  models:
    path: ../models
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  pro_lints: ^2.0.4
  retrofit_generator: ^9.1.4
