name: http_client
description: The http_client package.
publish_to: none
version: 1.0.0

environment:
   sdk: ^3.0.0

dependencies:
  dio: ^5.2.1+1
  fast_immutable_collections: ^9.1.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  models:
    path: ../models
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  pro_lints: ^2.0.1
  retrofit_generator: ^7.0.6