include: package:lint/common.yaml

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 80
  metrics-exclude:
    - test/**
  rules:
    - avoid-unnecessary-setstate
    - avoid-use-expanded-as-spacer
    - avoid-wrapping-in-padding
    - always-remove-listener
    - no-equal-arguments
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - prefer-single-widget-per-file
    - prefer-extracting-callbacks
    - prefer-correct-edge-insets-constructor
    - prefer-const-border-radius
    - prefer-conditional-expressions
    - prefer-extracting-callbacks
    - prefer-first
    - prefer-last
    - prefer-trailing-comma