name: app
description: App project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  async_redux: ^18.0.2
  business:
    path: ../business
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization:
    path: ../localization
  pro_validator: 1.0.0+1
  routemaster: ^1.0.1
  ui:
    path: ../ui
  utils:
    path: ../utils
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      
flutter:
  uses-material-design: true
