name: app
description: The App project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
   sdk: ^3.3.4

dependencies:
  async_redux: ^23.0.0
  business:
    path: ../business
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.0
  localization:
    path: ../localization
  pro_pretty_logging: ^1.0.6
  pro_validator: ^2.0.1
  ui:
    path: ../ui
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  pro_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    # BASE_URL="http://localhost:8080"
    - .env
