name: app
description: The App project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
   sdk: ^3.0.0
  
dependencies:
  async_redux: ^20.0.0
  business:
    path: ../business
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^7.1.1
  localization:
    path: ../localization
  pro_validator: ^1.1.1
  
  ui:
    path: ../ui
  utils:
    path: ../utils
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      
flutter:
  uses-material-design: true
