name: app
description: App project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  async_redux: ^15.0.0
  business:
    path: ../business
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization:
    path: ../localization
  routemaster: ^1.0.1
  ui:
    path: ../ui
  utils:
    path: ../utils
  validator:
    git:
      url: https://github.com/pro100andrey/validator.git
      ref: "aa06f69d01d31a2451d39a73a61074cd7d850749"
  
dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      href: '0e13a7c'
      
flutter:
  uses-material-design: true
