name: app
description: App project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  async_redux: ^16.0.0
  business:
    path: ../business
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization:
    path: ../localization
  routemaster: ^1.0.1
  ui:
    path: ../ui
  utils:
    path: ../utils
  validator:
    git:
      url: https://github.com/pro100andrey/validator.git
      ref: "03c17977487b087004155e8ab71a604a1eecb9f6"
  
dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_test:
    sdk: flutter
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      href: '41b64ec3bb748ec3b0fff7dba1ec31c5ee2db5fc'
      
flutter:
  uses-material-design: true
