name: storage
description: The storage package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  hive: ^2.2.3
  path_provider: ^2.0.14

dev_dependencies:
  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"
