name: storage
description: The internal storage.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  hive: ^2.2.3
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.3.2
  hive_generator: ^2.0.0
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"
