name: utils
description: The utils package.
publish_to: none
version: 1.0.0

environment:
   sdk: ^3.0.0
  
dependencies:
  logging: ^1.2.0
  
dev_dependencies:
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
