name: utils
description: The utils library.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  logging: ^1.0.2
  
dev_dependencies:
  dart_code_metrics: ^4.16.0
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
      href: '0e13a7c'
