name: utils
description: The utils package.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  logging: ^1.1.0
  
dev_dependencies:
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
