name: ui
description: The UI package.
publish_to: 'none'
version: 1.0.0

environment:
   sdk: ^3.2.0

dependencies:
  equatable: ^2.0.5
  extended_image: ^8.2.0
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.1
  localization:
    path: ../localization
  theme_extensions_builder_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.5.0+1
  pro_lints: ^2.0.4
  theme_extensions_builder: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/placeholders/
    # - assets/color/

flutter_gen:
  colors:
    inputs:
      - assets/color/light.xml
      - assets/color/dark.xml
  output: lib/generated/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
