name: ui
description: The UI package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  localization:
    path: ../localization
  
dev_dependencies:
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.2.0
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
  
flutter:
  uses-material-design: true
  assets:
    - assets/placeholders/
    - assets/colors/
    
flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml
  output: lib/generated/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true