name: ui
description: The UI package.
publish_to: 'none'
version: 1.0.0

environment:
   sdk: ^3.0.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  localization:
    path: ../localization
  
dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
  pro_lints: ^2.0.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/placeholders/
    - assets/colors/
    
flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml
  output: lib/generated/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true