name: ui
description: UI package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  
dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.1
  localization:
    path: ../localization
  
dev_dependencies:
  build_runner: ^2.1.4
  flutter_gen_runner: ^4.1.2
  flutter_test:
    sdk: flutter
  
  lint:
    path: ../lint
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/colors/
    
flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml
  output: lib/generated/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    package_parameter_enabled: true