name: ui
description: UI package
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.4
  localization:
    path: ../localization
  
dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.17.1
  flutter_gen_runner: ^4.3.0
  lint:
    git:
      url: 'https://github.com/pro100andrey/lint.git'
  
flutter:
  uses-material-design: true
  assets:
    - assets/placeholders/
    - assets/colors/
    
flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml
  output: lib/generated/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    package_parameter_enabled: true