name: ui
description: The UI package.
publish_to: 'none'
version: 1.0.0

environment:
   sdk: ^3.5.4

dependencies:
  equatable: ^2.0.5
  extended_image: ^9.0.4
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  localization:
    path: ../localization
  theme_extensions_builder_annotation: ^3.1.0
  vector_graphics: ^1.1.11+1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  pro_lints: ^2.0.4
  theme_extensions_builder: ^3.1.0
  vector_graphics_compiler: ^1.1.11+1

flutter_gen:
  output: lib/generated/
  colors:
    inputs:
      - assets/color/light.xml
      - assets/color/dark.xml
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  assets:
    - assets/vec/placeholders/
