name: models
description: The models package.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  fast_immutable_collections: ^9.0.0

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.6.1
  intl: ^0.18.0
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"