name: models
description: The models package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  fast_immutable_collections: ^9.1.3

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  intl: ^0.18.1
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"