name: models
description: The models package.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  fast_immutable_collections: ^8.0.0

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  intl: ^0.17.0
  lint:
    git:
      url: "https://github.com/pro100andrey/lint.git"

dependency_overrides:
  analyzer: ^5.2.0