name: models
description: The models package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.4.1

dependencies:
  fast_immutable_collections: ^10.2.3
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.10
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  pro_lints: ^2.0.4
